#!/usr/local/bin/bash
set -e
if [ "$(id -u)" != "0" ]; then
    echo ""
    echo " This script must be run as root" 1>&2
    echo ""
    exit 1
fi

NORMAL_USER=gandalf
CMD="nvim -n"
if [ -z "$1" ]; then
    echo expected filepath argument
    exit 1
fi
FILEPATH=$1
if [ ! -z "$2" ]; then
    shift 1
    CMD=$@
fi

FILE=$(basename $FILEPATH)
TMP_FOLDER=/tmp/aes-decrypted-dir/
DEST=$TMP_FOLDER/$FILE
mkdir -p $TMP_FOLDER
if [ ! -z "$(ls -A $TMP_FOLDER)" ]; then
    echo temporary folder $TMP_FOLDER not empty
    exit 1
fi
mount_mfs swap $TMP_FOLDER

printf "Password: "
stty -echo
read PASS
stty echo
echo

set +e
/home/$NORMAL_USER/.local/bin/aes -m ctr -p $PASS decrypt $FILEPATH $DEST
if [ $? -eq 0 ]; then
    chown $NORMAL_USER: $DEST
    doas -u $NORMAL_USER $CMD $TMP_FOLDER/$FILE
    /home/$NORMAL_USER/.local/bin/aes -m ctr -p $PASS encrypt $DEST $FILEPATH
fi
set -e
umount $TMP_FOLDER
